dhu = true
wired = "4e8:6860"
mitm = true
webserver = "0.0.0.0:8080"
ev = true
advertise = true
enable_btle = true
dongle_mode = false
debug = false
hexdump_level = "Disabled"
disable_console_debug = true
trace_channel_flow = true
legacy = true
quick_reconnect = false
bt_poweroff = false
connect = "00:00:00:00:00:00"
logfile = "/var/log/aa-proxy-rs.log"
stats_interval = 0
iface = "wlan0"
timeout_secs = 120
bt_timeout_secs = 120
dpi = 0
audio_max_unacked = 0
remove_tap_restriction = false
video_in_motion = false
disable_media_sink = false
disable_tts_sink = false
developer_mode = false
remove_bluetooth = false
remove_wifi = false
inject_display_types = "cluster"
inject_add_input_sources = true
inject_cluster_display_id = 1
inject_cluster_width_margin = 270
inject_cluster_height_margin = 344
inject_cluster_density = 180
inject_cluster_viewing_distance = 100
inject_cluster_touch_width = 1280
inject_cluster_touch_height = 720
inject_aux_display_id = 2
inject_aux_width_margin = 0
inject_aux_height_margin = 0
inject_aux_density = 160
inject_aux_viewing_distance = 300
inject_aux_touch_width = 1280
inject_aux_touch_height = 720
change_usb_order = false
stop_on_disconnect = false
waze_lht_workaround = false
ev_connector_types = ""
enable_ssh = true
usb_serial_console = false
wifi_version = 6
band = "5"
country_code = "US"
channel = 36
ssid = "aa-proxy"
wpa_passphrase = "aa-proxy"
eth_mode = ""
startup_delay = 0
ble_password = ""
external_antenna = false
media_dump_base_port = 12345
media_wait_for_live_idr = true
